---
title: "Opgave 2 - Lektion 4-6"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(zoo)
library(stringr)
library(ggrepel)
library(foreign)
library(AER)
library(lmtest)
library(sandwich)
library(texreg)
library(tseries)
library(timeSeries)
library(stats)
library(xts)
library(mFilter)
library(urca)
library(forecast)
library(strucchange)
library(Quandl)
library(tstools)
library(dynlm)
options(digits = 8)
options(scipen = 999)
rm(list=ls())
```

```{r, echo = F}
task = read.csv("TASK_mikro5.csv")
```

Opgave 1 tabel
```{r, echo = F}
task %>%
  mutate(ny_tek = ifelse(G1a == 1, 1, 0))
ny_tek = na.omit(ifelse(task$G1a == 1, 1, 0))

total_tek_yes <- sum(ny_tek)
total_tek_no <- length(ny_tek)-sum(ny_tek) # This counts 0s

summary_table <- data.frame(Response = c("Yes", "No"), Count = c(total_tek_yes, total_tek_no), Procent = c(total_tek_yes/length(ny_tek), total_tek_no/length(ny_tek)))
summary_table
```

